version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./files:/app/files
    environment:
      - PYTHONPATH=/app
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --workers 4 --loop uvloop --limit-concurrency 1000 --timeout-keep-alive 30 --access-log
